// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { resolve } from "path";
import { defineConfig } from "prisma/config";

const rootEnv = resolve(process.cwd(), ".env.local");
const defaultEnv = resolve(process.cwd(), ".env");

const loaded = config({ path: rootEnv });
if (!loaded.parsed) {
  config({ path: defaultEnv });
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
